/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -p org.gnome.SettingsDaemon.h:org.gnome.SettingsDaemon.cpp org.gnome.SettingsDaemon.xml org.gnome.SettingsDaemon.MediaKeys
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef ORG_GNOME_SETTINGSDAEMON_H_1371057472
#define ORG_GNOME_SETTINGSDAEMON_H_1371057472

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.gnome.SettingsDaemon.MediaKeys
 */
class OrgGnomeSettingsDaemonMediaKeysInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.gnome.SettingsDaemon.MediaKeys"; }

public:
    OrgGnomeSettingsDaemonMediaKeysInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgGnomeSettingsDaemonMediaKeysInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> GrabMediaPlayerKeys(const QString &in0, uint in1)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0) << QVariant::fromValue(in1);
        return asyncCallWithArgumentList(QLatin1String("GrabMediaPlayerKeys"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void MediaPlayerKeyPressed(const QString &in0, const QString &in1);
};

namespace org {
  namespace gnome {
    namespace SettingsDaemon {
      typedef ::OrgGnomeSettingsDaemonMediaKeysInterface MediaKeys;
    }
  }
}
#endif
